name: Release

on:
  push:
    tags:
      - v*

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install DBus
        run: sudo apt-get install -y libdbus-1-dev

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 'v1.x'

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SIMPLEBLE_C_SHARED=ON -B build -S SimpleBLE/simpleble

      - name: Build for Linux x64
        run: cmake --build build --config Release --parallel 4 --target simpleble-c

      - name: Upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./build/lib/libsimpleble-c.so

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.21.x'

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 'v1.x'

      - name: Configure CMake
        run: cmake -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DBUILD_SIMPLEBLE_C_SHARED=ON -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_BUILD_TYPE=Release -B build -S SimpleBLE/simpleble

      - name: Build for macOS arm64/x86_64
        run: cmake --build build --config Release --parallel 4 --target simpleble-c

      - name: Upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: lib/libsimpleble-c.dylib

  build-windows:
    runs-on: windows-2019
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 'v1.x'

      - name: Configure CMake
        run: cmake -G "Visual Studio 16 2019" -A x64 -DBUILD_SIMPLEBLE_C_SHARED=ON -DCMAKE_SYSTEM_VERSION=10.0.22000.0 -B build -S SimpleBLE/simpleble

      - name: Build for Windows x64
        run: cmake --build build --config Release --parallel 4 --target simpleble-c

      - name: Upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/lib/Release/simpleble-c.dll
