name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup Deno
      uses: denoland/setup-deno@main
      with:
        deno-version: 'v1.x'

    - name: Compile Lib for Windows x64
      run: |
        cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22000.0 -B build -S SimpleBLE
        cmake --build build --config Release --parallel 4
      shell: cmd

    - name: Build
      run: deno run -A --unstable ./build.ts
